data: 
  - ./data/nestquant
target: LABEL
date: OPEN_TIME
features: 
  - HIGH
  - LOW
  - CLOSE
  - VOLUME
  - QUOTE_ASSET_VOLUME
  - NUMBER_OF_TRADES
  - TAKER_BUY_BASE_ASSET_VOLUME
  - TAKER_BUY_QUOTE_ASSET_VOLUME
  - YEAR_AND_MONTH
  - ID
time_id: 
start_time_id: 
delimiter: ","
split_feature: ID
dir_as_feature: 0
split_dir_feature: 0
granularity: 60
time_format: 

year_start:
year_end:
month_start:
month_end:
day_start:
day_end:
hour_start: 
hour_end: 
minute_start:
minute_end:
